### ISSUE TITLE
UploadButton options type error

### ISSUE THREAD

**Issue by kincaidoneil** [upload-io/react-uploader#12]
`apiKey` isn't allowed on the options prop passed to UploadButton:

```
Type '{ apiKey: string; }' is not assignable to type 'UploadWidgetReactConfig'.
  Object literal may only specify known properties, and 'apiKey' does not exist in type 'UploadWidgetReactConfig'.
  
The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & UploadButtonProps'
```

[Simple reproduction, React/Vite/TypeScript@5.3](https://stackblitz.com/edit/vitejs-vite-patuta?file=src%2FApp.tsx&view=editor)

Other options work fine. I believe it has to do with how it's linking to the @bytescale/sdk types.

**Comment by ljwagerfield** [comment]
Thank you for the reproduction! 🎉 

Fixed in `@bytescale/upload-widget-react@^4.13.0` 👍 

[Simple reproduction (fixed)](https://stackblitz.com/edit/vitejs-vite-c9ea8d?file=src%2FApp.tsx)

(There were some [bad import statements](https://github.com/bytescale/bytescale-upload-widget/commit/58dd045966996069883fba7586cae796ae1b7008) affecting the links to the `@bytescale/sdk` types (as you highlighted).)
