### ISSUE TITLE
Customizable UploadDropzone component

### ISSUE THREAD

**Issue by hardcommitoneself** [upload-io/react-uploader#2]

**Comment by ljwagerfield** [comment]
Hi @hardcommitoneself !

Please can you provide a little more detail, with code examples?

Thanks!

**Comment by hardcommitoneself** [comment]
Hi, @ljwagerfield 

Can we implement the following features?

- customizable upload button(we can change the button style, name etc)
- trigger the upload button click event from outside of the drop zone component.

**Comment by ljwagerfield** [comment]
> we can change the button style, 

You can currently change the colour through [`styles.colors.primary`](https://github.com/upload-io/uploader#%EF%B8%8F-configuration) -

> name, etc

You can also change the text by providing a custom [localization object](https://github.com/upload-io/uploader#%EF%B8%8F-localization).

> trigger the upload button click event from outside of the drop zone component.

Do you mean, trigger the browser's native file uploader to open? (Since this is what the button's click event does.) If so, yes, we can think about adding this :)

**Comment by ljwagerfield** [comment]
Added support for a `className` prop in 3.4.0:

https://github.com/upload-io/react-uploader/releases/tag/v3.4.0
