### ISSUE TITLE
Customizable Dropzone

### ISSUE THREAD

**Issue by titusgahissy** [upload-io/react-uploader#5]
Hello,
I'm following up on issue #2.

1. Is it possible to customize this preview screen? Instead of showing a generic icon and the filename, maybe the actual uploaded image.  Developers should be able to do that through a `render` or parameterized `children` props

<img width="266" alt="Screenshot 2023-04-25 at 11 04 29" src="https://user-images.githubusercontent.com/140107/234244236-686009aa-de89-4910-8784-e951705dfd3c.png">

**Comment by ljwagerfield** [comment]
This would be an excellent feature!

We've also received interest in displaying custom progress (e.g. horizontal bars, instead of the circles we use currently).

The challenge is that [React Uploader](https://github.com/upload-io/react-uploader) is a simple wrapper for [Uploader](https://github.com/upload-io/uploader), which is a plain JavaScript library.

The [Uploader](https://github.com/upload-io/uploader) library is also extended by several other framework wrappers that we maintain (see below). 

Each framework wrapper provides a very similar API, and we really want to keep it this way.

Thus, the solution we choose essentially needs to be supported by 5 these libraries:

- [Uploader](https://github.com/upload-io/uploader)
- [React Uploader](https://github.com/upload-io/react-uploader)
- [Vue Uploader](https://github.com/upload-io/vue-uploader)
- [Angular Uploader](https://github.com/upload-io/angular-uploader)
- [jQuery Uploader](https://github.com/upload-io/jquery-uploader)

So whilst it's possible, I think it starts to get a little complicated, given the interop between each framework wrapper and the "plain JS" base component (which incidentally is written in Preact).

**Comment by ljwagerfield** [comment]
In general -- and because of the above -- we try to solve these issues by supporting the specific feature the user is after natively, rather than allowing areas of the component to accept arbitrary HTML.

In this case, it sounds like you want image thumbnails (instead of a generic icon)?

If so, we can certainly look into adding this.

**Comment by titusgahissy** [comment]
I opened the issue because I wanted to create the following UI that uses a grid instead of a list.

<img width="767" alt="Screenshot 2023-04-26 at 00 17 01" src="https://user-images.githubusercontent.com/140107/234427862-9af080da-0560-4378-958e-1bda2d1eb3eb.png">

**Comment by ljwagerfield** [comment]
Thanks for sharing :)

I don't think we'll be at a point (any time soon) where we can support UI changes as significant as this.

If you'd like to build a completely bespoke upload UI, you can use [Upload.js](https://upload.io/docs/upload-sdk/javascript) to handle file uploading, progress reporting, and cancellation.

It's a headless library, so you'd need to build the UI for yourself.

**Comment by titusgahissy** [comment]
Makes sense. I will explore this approach.
